### ISSUE TITLE
Configuration in TWIG template

### ISSUE THREAD

**Issue by timoberlin** [isometriks/IsometriksSpamBundle#14]
I would like to add the two features timed spam prevention and honeypot spam prevention in the login form of FOS User Bundle. Unfortunately, it seems not possible to override the Type of the login form with an only type based on AbstractType. Only the twig template seems to be available for customization. Is there any way to do add the two features (or at least the honeypot) only using twig?

**Comment by isometriks** [comment]
Sorry didn't see a notification for this. You should be able to do this with a from type extension if you haven't found a solution yet. The twig portion only sends variables to the view and not the building of the form itself.
