### ISSUE TITLE
Deprecation in Symfony 4.3

### ISSUE THREAD

**Issue by TomaszGasior** [isometriks/IsometriksSpamBundle#16]
After update to sf 4.3 I have this deprecation message in tests and profiler:

>  The "Symfony\Component\Config\Definition\Builder\TreeBuilder::root()" method called for the "isometriks_spam" configuration is deprecated since Symfony 4.3, pass the root name to the constructor instead.

**Comment by TomaszGasior** [comment]
@isometriks Pleate take a look at these commit to see how to fix this issue:
* https://github.com/symfony/maker-bundle/pull/324/commits/560d03cf68e3e9f1b9c4436e9c51572459fef1a3
* https://github.com/doctrine/DoctrineBundle/pull/853/commits/e711bed5a82437262aeade06373fcd5c81a2fd94

**Comment by isometriks** [comment]
Can you make a PR?
