### ISSUE TITLE
0.3.0 broke on sf2.3

### ISSUE THREAD

**Issue by arendjantetteroo** [isometriks/IsometriksSpamBundle#2]
I've just updated composer and it installed 0.3.0 for your bundle. 
However this fails on 2.3 with an exception: 

http://gyazo.com/ecff14441f0d4eafefc9b1c07f5b6f6a

Can you update your composer.json to mark 0.3.0 as sf2.7+ only? 
Or check if you can keep BC for 2.3?

**Comment by isometriks** [comment]
Ah yeah, probably because I removed the setDefaultOptions. I can try to resolve that soon.

**Comment by arendjantetteroo** [comment]
Cool, thanks in advance

**Comment by isometriks** [comment]
@arendjantetteroo try out 0.3.1 now should be fixed
