### ISSUE TITLE
FormTypeTimedSpamExtension::__construct() must be an instance TranslatorInterface 

### ISSUE THREAD

**Issue by insekticid** [isometriks/IsometriksSpamBundle#25]
Symfony 5.1, and IsometriksSpamBundle v1.05

Argument 2 passed to Isometriks\Bundle\SpamBundle\Form\Extension\Spam\Type\FormTypeTimedSpamExtension::__construct() must be an instance of Symfony\Component\Translation\TranslatorInterface or null, instance of Symfony\Component\Translation\DataCollectorTranslator given, called in /var/www/html/var/cache/dev/Container8qV3Awa/getIsometriksSpam_Form_Extension_Type_TimedSpamService.php on line 26

EDIT:
Use use Symfony\Contracts\Translation\TranslatorInterface; instead of Symfony\Component\Translation\TranslatorInterface

**Comment by isometriks** [comment]
Hm whoops. I just pushed 1.0.6, sorry about that.

**Comment by insekticid** [comment]
great, now it works!
