### ISSUE TITLE
Drop support for symfony 4.4

### ISSUE THREAD

**Issue by maelanleborgne** [isometriks/IsometriksSpamBundle#34]
[Symfony 4.4](https://symfony.com/releases/4.4) is coming to [the end of it's security fix support](https://endoflife.date/symfony), it is not recommended to use this version anymore, 5.4 is the current LTS version and 6.4 is just around the corner.
I'd be happy to drop 4.4 support and release a new version so that 4.4 users can keep using this bundle in it's 1.1.0 version, while we add new updates for 5.4 / 6.* / 7.0 only.
That will make it easier for developers who want to contribute, since juggling with compatibility isn't easy (and there's a big gap between 4.4 and 7.0).

**Comment by ThomasLandauer** [comment]
Ping @isometriks This is more urgent now, since Symfony 7.0 was released already.
