### ISSUE TITLE
Does not work with Symfony3

### ISSUE THREAD

**Issue by treetop1500** [isometriks/IsometriksSpamBundle#4]
Thanks for the great bundle.  Just recently tried to adopt to Symfony3 and...

The form.type_extension tag configuration for the timed and honeypot methods doesn't included the extended-type argument and throws an exception.

`
InvalidArgumentException in FormPass.php line 59: Tagged form type extension must have the extended type configured using the extended_type/extended-type attribute, none was configured for the "isometriks_spam.form.extension.type.honeypot" service.`

**Comment by insekticid** [comment]
fixed int #5

**Comment by isometriks** [comment]
Should be working now for ~1.0
