### ISSUE TITLE
Are the messages translatable?

### ISSUE THREAD

**Issue by peyman-mohamadpour** [isometriks/IsometriksSpamBundle#8]
Have you added i18n feature?

**Comment by isometriks** [comment]
Yes, it works:

https://github.com/isometriks/IsometriksSpamBundle/blob/master/Form/Extension/Spam/EventListener/HoneypotValidationListener.php#L39

It uses the translation domain of the validator:

https://github.com/isometriks/IsometriksSpamBundle/blob/master/Resources/config/honeypot.xml#L15
